name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: |
            ## What's Changed

            $CHANGES

            ## New Contributors

            $CONTRIBUTORS

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
